import { describe, expect, it } from 'vitest'

import { FEE_RATE, generateReference, netCredit, parseAmountToMinorUnits, processingFee } from '@/lib/fees'

describe('processingFee', () => {
  /**
   * Parity table generated by running App\Support\Fees::processingFee in the
   * Laravel app, not by reading this implementation. If the two ever diverge,
   * the payment form would promise the operator a figure the API will not
   * honour, so these are the values that matter most in the suite.
   *
   * Worth knowing: these assertions cannot distinguish the integer expression
   * from Math.round(gross * 0.015), because a sweep of the whole accepted
   * range found no input where the two differ. They do catch a changed rate,
   * a changed rounding direction, and off-by-one errors.
   */
  const parityWithBackend: [gross: number, fee: number][] = [
    [1, 0],
    [33, 0],
    [34, 1],
    [50, 1],
    [100, 2],
    [101, 2],
    [150, 2],
    [200, 3],
    [300, 5],
    [500, 8],
    [999, 15],
    [10_000, 150],
    [12_345, 185],
    [123_457, 1_852],
    [250_000, 3_750],
    [999_999, 15_000],
    [1_000_000, 15_000],
    [100_000_000, 1_500_000],
  ]

  it.each(parityWithBackend)('charges %i pesewas a fee of %i, matching the backend', (gross, fee) => {
    expect(processingFee(gross)).toBe(fee)
  })

  it('rounds a half pesewa up', () => {
    // 100 * 1.5% is exactly 1.5; float maths here is the thing being avoided.
    expect(processingFee(100)).toBe(2)
    expect(processingFee(300)).toBe(5) // exactly 4.5
    expect(processingFee(500)).toBe(8) // exactly 7.5
  })

  it('rounds below a half pesewa down', () => {
    expect(processingFee(33)).toBe(0) // 0.495
    expect(processingFee(233)).toBe(3) // 3.495
  })

  it('always returns a whole number of pesewas', () => {
    for (let gross = 1; gross <= 2_000; gross += 7) {
      expect(Number.isInteger(processingFee(gross))).toBe(true)
    }
  })

  it('never exceeds the gross amount', () => {
    for (const [gross] of parityWithBackend) {
      expect(processingFee(gross)).toBeLessThanOrEqual(gross)
    }
  })

  it('is monotonic — a larger payment never costs a smaller fee', () => {
    let previous = 0
    for (let gross = 0; gross <= 50_000; gross += 13) {
      const fee = processingFee(gross)
      expect(fee).toBeGreaterThanOrEqual(previous)
      previous = fee
    }
  })

  it('states the rate as 1.5%', () => {
    expect(FEE_RATE).toBe(0.015)
  })
})

describe('netCredit', () => {
  it('is the gross less the fee', () => {
    expect(netCredit(10_000)).toBe(9_850)
    expect(netCredit(123_457)).toBe(121_605)
  })

  it('always reconciles: net + fee === gross', () => {
    for (let gross = 1; gross <= 100_000; gross += 997) {
      expect(netCredit(gross) + processingFee(gross)).toBe(gross)
    }
  })
})

describe('parseAmountToMinorUnits', () => {
  it.each([
    ['250', 25_000],
    ['250.00', 25_000],
    ['0.01', 1],
    ['1234.57', 123_457],
    ['1,234.57', 123_457],
    ['  99.90  ', 9_990],
    ['.5', 50],
  ])('parses %s into %i pesewas', (input, expected) => {
    expect(parseAmountToMinorUnits(input)).toBe(expected)
  })

  it.each([
    ['', 'empty'],
    ['   ', 'whitespace only'],
    ['.', 'bare decimal point'],
    ['abc', 'letters'],
    ['12.345', 'more than two decimals'],
    ['-5', 'negative'],
    ['0', 'zero'],
    ['0.00', 'zero with decimals'],
    ['1e3', 'exponent notation'],
  ])('rejects %s (%s)', (input) => {
    expect(parseAmountToMinorUnits(input)).toBeNull()
  })

  it('round-trips through the fee calculation without drift', () => {
    const minorUnits = parseAmountToMinorUnits('2450.00')!

    expect(minorUnits).toBe(245_000)
    expect(processingFee(minorUnits)).toBe(3_675)
    expect(netCredit(minorUnits)).toBe(241_325)
  })
})

describe('generateReference', () => {
  it('is prefixed and of a fixed length', () => {
    const reference = generateReference()

    expect(reference).toMatch(/^PAY-[A-Z2-9]{10}$/)
  })

  it('omits characters that are easy to misread aloud or by eye', () => {
    const alphabet = Array.from({ length: 400 }, generateReference).join('')

    // No 0/O or 1/I — references get read out and typed by hand.
    expect(alphabet).not.toMatch(/[01IO]/)
  })

  it('does not collide across a realistic batch', () => {
    const batch = new Set(Array.from({ length: 1_000 }, generateReference))

    expect(batch.size).toBe(1_000)
  })
})
